AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: sample script to demo dynamodb streams functionality

Resources:

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      StreamSpecification: 
        StreamViewType: NEW_AND_OLD_IMAGES
      ProvisionedThroughput:
        WriteCapacityUnits: 5
        ReadCapacityUnits: 5
      AttributeDefinitions:
        - AttributeName: "pk1"
          AttributeType: "S"
        - AttributeName: "sk1"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "pk1"
          KeyType: "HASH"
        - AttributeName: "sk1"
          KeyType: "RANGE"
  
  StreamsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: streamsdemo/streamsdemo.lambda_handler
      Runtime: python3.8
      Timeout: 3
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref DynamoDBTable
      CodeUri: .
      Events:
        DynamoDBEvent:
          Type: DynamoDB
          Properties:
            Stream:
              !GetAtt DynamoDBTable.StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 1